name: CI

on:
  schedule:
    - cron: "0 20 * * 1"
  push:
    tags:
      - v*
    branches:
      - main
      - master

jobs:
  specs:
    runs-on: ubuntu-latest
    # container: crystallang/crystal:latest
    steps:
      - uses: actions/checkout@v3
      - name: Start SurrealDB
        uses: docker run -it -d --rm --name surrealdb -p 8000:8000 surrealdb/surrealdb start -u root -p root
      - run: crystal --version
      - run: shards install
      - name: specs
        env:
          SURREALDB_URL: http://localhost:8000/sql
        run: crystal spec --error-on-warnings
        
  check_format:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: crystal tool format --check
