name: CI

on:
  schedule:
    - cron: "0 20 * * 1"
  push:
    tags:
      - v*
    branches:
      - main
      - master
permissions:
  contents: read

jobs:
  specs:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest
    services:
      surreal-db:
        image: surrealdb/surrealdb
        ports:
          - 8000:8000
        options: >-
          --user root
          --pass root
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - run: crystal --version
    - run: shards install
    - name: specs
      env:
        SURREALDB_URL: http://localhost:8000/sql
      run: crystal spec --error-on-warnings

  check_format:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest-alpine
    steps:
    - uses: actions/checkout@v3
    - run: crystal tool format --check
