name: CI

on:
  schedule:
    - cron: "0 20 * * 1"
  push:
    tags:
      - v*
    branches:
      - main
      - master

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: nightly}
          - {os: macos-latest}
          - {os: windows-latest}
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Start SurrealDB
        run: docker run -it -d --rm --name surrealdb -p 8000:8000 surrealdb/surrealdb start -u root -p root
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - run: crystal --version
      - run: shards install
      - name: specs
        env:
          SURREALDB_URL: http://localhost:8000/sql
        run: crystal spec --error-on-warnings
      - run: crystal tool format && git diff --exit-code
        if: matrix.crystal == 'latest'

  check_format:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: crystal tool format --check
