name: CI

on:
  schedule:
    - cron: "0 20 * * 1"
  push:
    tags:
      - v*
    branches:
      - main
      - master

jobs:
  specs:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest
    steps:
      - uses: actions/checkout@v3
      - name: Start SurrealDB
        uses: docker://surrealdb/surrealdb:latest
        options: >-
          -d 
        with:
          args: start -u root -p root memory
      - run: crystal --version
      - run: shards install
      - name: specs
        env:
          SURREALDB_URL: http://localhost:8000/sql
        run: crystal spec --error-on-warnings
        
  check_format:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: crystal tool format --check
