name: CI

on:
  schedule:
    - cron: "0 20 * * 1"
  push:
    tags:
      - v*
    branches:
      - main
      - master

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly, 0.35.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start SurrealDB
        run: docker run -it -d --rm --name surrealdb -p 8000:8000 surrealdb/surrealdb start -u root -p root
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - run: crystal --version
      - run: shards install
      - name: specs
        env:
          SURREALDB_URL: http://localhost:8000/sql
        run: crystal spec --error-on-warnings
      - run: crystal tool format --check